server:
  weather-cache-evict-cron: 0 0 3 * * *
  port: 8000

bot:
  webhook-path: https://f0c2-194-226-248-0.ngrok-free.app
  token: 6059530887:AAFHPmDyT_obKiD-uI2TSUMGnRzSV-n11PE
  name: Weatherfy
  most-popular-cities: Екатеринбург,Москва,Санкт Петербург,Казань,Краснодар

weatherApi:
  protocol: http
  host: api.openweathermap.org
  weatherEndpoint: /data/2.5/weather
  forecastEndpoint: /data/2.5/forecast
  geoEndpoint: /geo/1.0/direct
  token: b3aad3b9c2d7988afae46a7f1973b6d7
  units: metric
  forecastStepInHours: 3
  timestamps-in-api-response: 40
